version: '3.9'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '192.168.74.184:8000:8000'
      - '192.168.74.184:8001:8001'
      - '192.168.74.184:8020:8020'
      - '192.168.74.184:8030:8030'
      - '192.168.74.184:8040:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: password
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      GRAPH_LOG: info
      GRAPH_ETHEREUM_GENESIS_BLOCK_NUMBER: 8743660
      ethereum: 'decimal-testnet:https://testnet-val.decimalchain.com/web3/'
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '192.168.74.184:5001:5001'
      - '192.168.74.184:8080:8080'
    volumes:
      - ./mounts/ipfs:/data/ipfs
  postgres:
    image: postgres:15-alpine
    ports:
      - '192.168.74.184:5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: password
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./mounts/db:/var/lib/postgresql/data
